name: '1sa Terraform-Apply'
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/1sa-apply.yml
      - towers/analytics/1sa.tfvars
      - modules/**
jobs:
  terraform-apply-job:
    name: '1sa Terraform-Apply'
    uses: mondelez-ctiso/gcp-devops-templates/.github/workflows/terraform-environment-apply.yml@v1.latest
    secrets: inherit
    with:
      ENV_VAR_FILE: towers/analytics/1sa.tfvars towers/analytics/common.tfvars
      PLAN_NAME: 1sa.tfplan
      PREFIX: terraform/onboarding/analytics/1sa
      TF_STATE_BUCKET: core-org-tfstate-52fe
      WORKFLOW_FILE: 1sa-apply.yml
      GITHUB_ENVIRONMENT: main
