name: '{{var.projectName}} Terraform-Plan'
on:
  pull_request:
    branches:
      - development
      - master
    paths:
      - .github/workflows/{{var.projectName}}-plan.yml
      - towers/analytics/{{var.projectName}}.tfvars
      - modules/**
jobs:
  terraform-plan-job:
    name: '{{var.projectName}} Terraform-Plan'
    uses: mondelez-ctiso/gcp-devops-templates/.github/workflows/terraform-common-plan.yml@v1.latest
    secrets: inherit
    with:
      ENV_VAR_FILE: towers/analytics/{{var.projectName}}.tfvars towers/analytics/common.tfvars
      PLAN_NAME: {{var.projectName}}.tfplan
      PREFIX: terraform/onboarding/analytics/{{var.projectName}}
      TF_STATE_BUCKET: core-org-tfstate-52fe
      WORKFLOW_FILE: {{var.projectName}}-plan.yml
