name: '{{var.projectName}} Terraform-Apply'
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/{{var.projectName}}-apply.yml
      - towers/analytics/{{var.projectName}}.tfvars
      - modules/**
jobs:
  terraform-apply-job:
    name: '{{var.projectName}} Terraform-Apply'
    uses: mondelez-ctiso/gcp-devops-templates/.github/workflows/terraform-environment-apply.yml@v1.latest
    secrets: inherit
    with:
      ENV_VAR_FILE: towers/analytics/{{var.projectName}}.tfvars towers/analytics/common.tfvars
      PLAN_NAME: {{var.projectName}}.tfplan
      PREFIX: terraform/onboarding/analytics/{{var.projectName}}
      TF_STATE_BUCKET: core-org-tfstate-52fe
      WORKFLOW_FILE: {{var.projectName}}-apply.yml
      GITHUB_ENVIRONMENT: main
